api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 10
